### ISSUE TITLE
Slovníček: Zvýraznění hledaného slova

### ISSUE THREAD

**Issue by pionl** [cesko-digital/movapp-apple#1]
<img width="365" alt="Snímek obrazovky 2022-04-04 v 10 38 36" src="https://user-images.githubusercontent.com/1878831/161506547-27585acd-43fc-429d-9a45-9dcc96dfe25d.png">

**Comment by pionl** [comment]
@met má se dělat?

**Comment by met** [comment]
Přemýšlím, že to možná není vůbec nutné.
Na webu to mělo zprvu smysl, i to připomíná chováni browseru při hledání, ale na mobilu to možná nepotřebujeme. 

Klidně bych to vynechal.
