### ISSUE TITLE
Onboarding nemá viditelný status bar

### ISSUE THREAD

**Issue by kubito** [cesko-digital/movapp-apple#103]

**Comment by kubito** [comment]
@pionl Zkoumal jsem to a možné řešení:

1. Dát tam pod to ošklivý proužek jako máme v nastavení
2. Předělat na všech screenách navigation bar tak aby se zobrazoval nadpis a nahradit modrou hlavičku stejným pozadím (stejně jak to mají nativní aplikace od Apple)
3. Zkusit to vyřešit v rámci Dark mode

**Comment by pionl** [comment]
@kubito co si myslíš že bude vypadat dobře? Já bych udělal 1. aby to drželo "skoro" design co navrhli UX/UI.

**Comment by kubito** [comment]
@pionl Druhá možnost, aspoň mě se líbí více nativní aplikace od Apple, je to takové čistější. Jen bude docela výzva předělat Slovníček a Abeceda aby to fungovalo co nejlépe. Ale bohužel by se to hodně odlišilo od Android appky a možná i trochu s brandem :/

Můžu kdyžtak udělat bod 1. to bude rychlé a asi to ani moc neurazí.

**Comment by pionl** [comment]
jj proto bych udělal bod 1. Ten onboarding je minoritní část aplikace a časem třeba upustíme bíle pozadí aby se to vyřešilo :)
