### ISSUE TITLE
Vánoční ikona

### ISSUE THREAD

**Issue by kubito** [cesko-digital/movapp-apple#120]
Od prosince do poloviny ledna.

https://www.hackingwithswift.com/example-code/uikit/how-to-change-your-app-icon-dynamically-with-setalternateiconname

**Comment by pionl** [comment]
To je skvělé :)

**Comment by met** [comment]
@pionl on bude i vánoční obsah, viz zápisy z callů, ta ikonka je třešinka na dortu aplikace 😊
