### ISSUE TITLE
SoundService a obecné handlování zvuků

### ISSUE THREAD

**Issue by kubito** [cesko-digital/movapp-apple#145]
- [x] Přesunout slučování cest ke zvukovým souborům ze SoundService.
- [x] Cestu k alphabet zvukům brát přímo z jsonu a zparsovat - stejně jako je tomu u dictionary.

**Comment by pionl** [comment]
> Cestu k alphabet zvukům brát přímo z jsonu a zparsovat - stejně jako je tomu u dictionary.

to si myslím že je dobrý nápad, aspoň to bude pěkně sjednocené 👍
