### ISSUE TITLE
Zprovoznit překlad bez podepisování

### ISSUE THREAD

**Issue by zoul** [cesko-digital/movapp-apple#15]
Aktuálně to máme nastavené tak, že každý překlad v Xcode vyžaduje podpisy. To je hloupé kvůli novým přispěvatelům, kterým takhle házíme klacky pod nohy. Dalo by se to nastavit tak, aby mohl kdokoliv po běžném checkoutu spustit aplikaci na simulátoru? (Zavést třeba novou výchozí konfiguraci?)

**Comment by pionl** [comment]
> Xcode vyžaduje podpisy

Co tím myslíš? asi tomu nerozumím. Myslíš tím výchozí "jazyk"?

Nebo překlady UI?

Myslím si, že cílem je spíš udělat následující (pro "slovníček"):

- mít backend kde bude na to UI
- v test flight verzi bude možné se podívat i na preview jazyky a vynutit aktualizaci

Nedokážu si moc představit že reálně budou všichni mít Mac / Xcode.

Co se týče překladů UI - tady bych šel exportem od vývojáře (klidně může být asi pak i action) a použití nějakého editoru (pokud překladatel nemá Xcode) -> https://gist.github.com/martnst/8597b27bb52baf00f1ef

**Comment by zoul** [comment]
Pardon, nenapsal jsem to jasně – myslím code signing.

**Comment by pionl** [comment]
Ted to chápu :)

Jj můžeme udělat nové schéma a dev tým si to bude muset přepnout?

**Comment by pionl** [comment]
@pistelak toto jste s @zoul probírali - tady je na to task

**Comment by pistelak** [comment]
Ahojte, 

díval jsem se na to, ale nejsem si jistý, že to lze jednoduše v dnešní době udělat. Možná mi něco uniká - projektový soubor je peklo 😅, tzn. pokud mě můžete nakopnout správným směrem, tak do toho... 

Hlavní důvod je, že team "Signing" se nastavuje pro target a ne pro schéma. Asi bychom mohli udělat i nový target, ale to bych asi nedoporučoval ať se nám nerozchází "dev" a release konfigurace. 

Nicméně v současném stavu není problém buildit appku na simulátor a používat náhledy - jediný problém co by navrhované řešení vyřešilo je že by červeně "Provisioning Profile" v nastavení projektu, ale to mi osobně asi zase tak moc nevadí. 

Co myslíte?

**Comment by zoul** [comment]
Aha, já jsem totiž nezkoušel, jak to bez těch certifikátů chodí. Myslel jsem, že to skončí chybou i při buildu pro simulátor – pokud ne, tedy pokud se to dá po čerstvém checkoutu pustit na simulátoru, tak super a dál bych neřešil.

**Comment by pistelak** [comment]
> tedy pokud se to dá po čerstvém checkoutu pustit na simulátoru, tak super a dál bych neřešil.

Dřív by tuším stačilo přepnout profil na osobní, ale teď jsem nemusel dělat nic a funguje to...  :) Pokud se neobjeví problémy, tak bych to taky neřešil.

**Comment by zoul** [comment]
Supr, tak já zavírám a kdybychom narazili na nějaký zádrhel později, můžeme vrátit do hry. Díky!
