### ISSUE TITLE
Dictionary not loading its content

### ISSUE THREAD

**Issue by matuyka** [cesko-digital/movapp-apple#174]
**Summary**
[When you change the language in the settings and navigate to the "For Kids" section, the dictionary does not load its content.]

**To Reproduce**
[1. Open the app
2. Go to the For Kids
3. Click on Vocabulary
4. Go on Settings
5. Change the language to Polish
6. Click on For Kids]

**Expected behavior**
[After clicking on For Kids, you should see the words in Ukrainian and Polish with the option to play them and the corresponding image]

**Version/Build number**
[1.6.0, build 54.]

**Attachments**
![54C11BA2-0630-4259-82C4-BCD5C2E19BAC](https://user-images.githubusercontent.com/98667082/233996640-5ac7b799-060a-4f0b-9e76-e19e0a484266.png)

**Comment by kubito** [comment]
@matuyka Could you please check it again on the version where is implemented the memory game? Is this issue still happening?

**Comment by matuyka** [comment]
@kubito I checked it with the latest version, and it is no longer happening.
