### ISSUE TITLE
Slovníček: Scoring frází při hledání a jejich řazení

### ISSUE THREAD

**Issue by pionl** [cesko-digital/movapp-apple#2]
- Větší skóre přiřadit kratšímu slovu?
- Implementovat nějaký text similarity https://en.wikipedia.org/wiki/Levenshtein_distance ?

**Comment by met** [comment]
Možná by stačilo řadit to podle podíl dvou čísel: počet matchnutých znaků / počet všech znaků řetězce
Slovně řečeno větší match = větší score

V text similarity se nevyznám, ale pokud s tím máš dobrou zkušenost, tak klidně to použij.

**Comment by pionl** [comment]
Ještě jsem to nepoužil, bavil jsem se s kolegou co dělá web aplikaci na učení slovíček a ten šel třeba svoji logikou (pro nás moc komplikované).

Klidně můžeme začít nečím jednoduchým a pak zkusit toto. Našel jsem i implementace ve swiftu :)

**Comment by pionl** [comment]
Změnit priority:

- oblíbené
- přesný match na slovo
- leveinshtein
