### ISSUE TITLE
Pexeso - cards could speak after game ends

### ISSUE THREAD

**Issue by met** [cesko-digital/movapp-apple#209]
When pexeso games is finished, the final music and animation is played and then all remains still. The only action posible now is to press New game button (situations is displayed at the picture).

I suggest that cards in this stage remains "active". The user could touch cards and they should speak - without animation, just say its name. In this way user can repeat words which he still does not remember.

<img width="606" alt="image" src="https://github.com/cesko-digital/movapp-apple/assets/59498/f93c2d4b-414e-4083-b3d6-0ff101d262aa">

**Comment by xergic** [comment]
I would suggest subtle animation when tapping a card - just scale effect - to provide some feedback. Or even haptics (iPhone only).

We could also add haptics when user finds a pair (success type) or when fails to do so (warning or error type). But that should be a separate task.
