### ISSUE TITLE
Homescreen widget

### ISSUE THREAD

**Issue by pionl** [cesko-digital/movapp-apple#24]
- [x] Poladit texty při konfiguraci widgetu
    - [x] UK text je z google translatoru, je potřeba doplnit zvalidovaný text
- [x] Dlouhé texty vytékají mimo widget
- [ ] Example na základě zvoleného jazyka
- [x] Proklik do appky viz komentář or MartinaH
    - [x] vyřešeno pomoci searche, není to nejlepší ředění, ale pro většinu případů by to mělo stačit.

**Comment by kubito** [comment]
WIP je připravené v #36. Jednou za hodinu to dá náhodnou frázi ze slovníčku. Jako další krok může být druhá konfigurace widgetu, kde budou oblíbené fráze nebo obrázky s textací pro děti.

**Comment by met** [comment]
Tip na zlepšení: Když teď kliknu na widget, otevře se mi Movapp na základní obrazovce. Čekal bych, že se otevře přímo na tom slovíčku z widgetu.
Důvod: vidím na widgetu zajímavé slovíčko, tak na něj kliknu, abych si ho přidal do oblíbených nebo si přehrál výslovnost.

**Comment by kubito** [comment]
- [ ] Poladit texty při konfiguraci widgetu
- [ ] Dlouhé texty vytékají mimo widget

**Comment by kubito** [comment]
Uzavírám, jakmile dojde nějaký feedback vyřešíme ho kdyžtak v separe issue.
