### ISSUE TITLE
Přidání seznamu přispěvatelů

### ISSUE THREAD

**Issue by pionl** [cesko-digital/movapp-apple#55]
Do aplikace by jsme chtěli dát členy týmu - v rámci této úpravy navrhuji udělat jednotnou strukturu json, kterou si pak v budoucnu klidně bude stahovat aplikace.

Struktura by byla formou předem domluvených "skupin":

- Vývoj Apple aplikace
- Vývoj Android aplikace
- Vývoj webu
- Tvorba obsahu
- Ostatní?

Dal bych tam pouze seznam jmen? Chceme dát i odkaz na nějaká profil? Json bude podporovat i případně společnosti.

```json
{
    "data": [
       {
               "section": {"name": "Vývoj Apple aplikace"},
               "persons": [{"name": "František"}]
       }
     ]
}
```

Souhlas? @met

**Comment by met** [comment]
Udělal jsem [seznam i s dílčími týmy](https://trello.com/c/4iGwqL2k/145-t%C3%BDm-do-ios-aplikace-form%C3%A1t-a-seznam), v neděli si to ještě s Martinou odsouhlasíme.

**Comment by pionl** [comment]
Více v PR #79

Taky jsem přidal sdílené data do movapp-data - [team.json](https://github.com/cesko-digital/movapp-data/blob/main/team.json), [schema](https://github.com/cesko-digital/movapp-data/blob/main/team.schema.json)

**Comment by pionl** [comment]
Hotovo
