### ISSUE TITLE
Slovníček: Přidat historii

### ISSUE THREAD

**Issue by pionl** [cesko-digital/movapp-apple#6]
Přidávat pouze přehrané

@met Co myslíš?

**Comment by met** [comment]
Přemýšlím, jestli to nejsou dvě věci.
Historie hledání a historie přehrávání. Dokud to nevidím před sebou nejsem si jistý, zda je OK je zaměňovat.

Když budou lidé často offline, tak budou moct jen hledat a přesto by čekali, že uvidí něco v historii, ač nic nepřehrávali.

**Comment by met** [comment]
Pravda, u okamžitého vyhledávání je to složité.
Hledám jak to dělá ta kupa slovníčků, co mám na iOS nainstalovaných a oni to řešit nemusí, protože tam vždy mají nějaký předstupeň, např. psaní výrazu zobrazí rychlý našeptávač a teprve po prokliku je vidět nalezený záznam, to ale nechceme.

Hmm, mohli bychom jako “podmínku přidání do historie” považovat jakoukoliv interakci s výsledky vyhledávání?
Přehrání zvuku je jedna možnost, ale ono i scrollování dolů mezi výsledky znamená, že mě zajímají. Nebo přidání do oblíbených. Vlastně jakákoliv touch interakce do výsledků vyhledávání by se dal brát jako postačující podmínka pro přidání do historie. Dává to smysl? Není to složité na implementaci?

**Comment by pionl** [comment]
Teoreticky asi by to šlo, v podstatě to co viděl by tam možná šlo dát. Můžeme tím začít, třeba pak můžeme "měřit" jak dlouho to "viděl" na obrazovce.

**Comment by met** [comment]
Já si nejsem stále jistý, jestli ti dobře rozumím. Zkusil jsem udělat pro přiklad krátké video a připravovaným novým hledáním (ono to děláš asi takhle podobně, že?), zkuste si to rozmyslet u něj.

https://user-images.githubusercontent.com/59498/161552674-8aa9c8b5-7963-4fe9-a4cf-4d8facee820b.mp4

Na videu: Píšu do hledání **p**,**e**,**n**. Postupně mi to filtruje výsledky. Pak si přehraji větu "Kde si mohu směnit peníze?".

V **historii hledání** by tak asi mělo být **pen** (nikoliv samotné **p** ani **pe**, protože to jsem jen postupně psal, což jde poznat třeba tak, že jsem pokračoval v psaní a s ničím jsem neinteragoval). Pen sice není celé slovo, ale hledání toho výrazu mě uspokojilo (interagoval jsem s výsledky).

Naopak **historie přehrávávání** by obsahovala jen "Kde si mohu směnit peníze?" 

A já si nejsem jistý, jakou z těch historií chceš implementovat.
Možná chceš dokonce mix obojího? Já bych to nechal jako dvě odlišné věci, nebo implementoval jen jednu z nich?

**Comment by met** [comment]
Můžeme tuhle možnost volbu taky prozatím odložit. Některá rozhodnutí se dělají snáz, když vidíš uživatele, jak aplikaci používají. Třeba nám to pak bude jasné jak facka a teď bychom jen vymyšleli?
