### ISSUE TITLE
Chybějící ikona pro Watch app

### ISSUE THREAD

**Issue by zoul** [cesko-digital/movapp-apple#63]
App Store mě poslal k šípku, že nám chybí ikona:

> ITMS-90713: Missing Info.plist value - A value for the Info.plist key 'CFBundleIconName' is missing in the bundle 'cz.movapp.app.watchkitapp'. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7.

@pionl, mrkneš na to, prosím?

**Comment by pionl** [comment]
jdu na to

**Comment by pionl** [comment]
@zoul hotovo #66

**Comment by pionl** [comment]
Můžeme udělat nový release?

**Comment by zoul** [comment]
Zkusím, ať vidíme, jak to funguje.

**Comment by zoul** [comment]
OMG ten Apple nás dobře trollí 💩 

> ITMS-90713: Missing Info.plist value - A value for the Info.plist key 'CFBundleIconName' is missing in the bundle 'cz.movapp.app.watchkitapp'. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7.

To je úplně to stejné, že?

**Comment by pionl** [comment]
😓 přidal jsem to tam, špatně jsem to pochopil a přidal jenom ikony. Odeslal jsem to manuálně do Appstore a už to prošlo

**Comment by zoul** [comment]
Ono to projde, tj. App Store ten build akceptuje, ale pak přijde reklamace později. A přišla zas, ohledně buildu 3, tak co můžem dělat špatně? 🤔 (BTW klidně tyhle fixy vydávej přes standardní proces tady na GitHubu, ať vidím, co do toho App Storu šlo. Takhle mně chodí notifikace ohledně buildů, které nevidím na GitHubu.)

**Comment by pionl** [comment]
Ale takhle bych to musel dávat pokaždé do release branche že?

**Comment by pionl** [comment]
@zoul Přidal jsem to všude https://github.com/cesko-digital/movapp-apple/commit/c3f03e319c798bd3c0aaf306f34fe61c067a5f58

**Comment by zoul** [comment]
Za mě to není nutné, důležité je vidět ten commit a tag. Takže pokud uděláš u sebe nějaký merge a pushneš ho do release větve, nemám s tím problém.

**Comment by pionl** [comment]
Chápu :)
