### ISSUE TITLE
Automatizace PR release

### ISSUE THREAD

**Issue by pionl** [cesko-digital/movapp-apple#74]
- Lokálně udělat `bundle exec fastlane release` a pushnu změny s tagem (možná by to rovnou mohl udělat ten command
- Github action spustí toto https://github.com/marketplace/actions/create-pull-request
- Vezme se commit message jako title (což vždy bude Release XX) `${{ github.event.head_commit.message }}` (https://stackoverflow.com/a/67145320)
- Script automaticky udělá novou branch který se pak smaže (release/TAG?) -> do `release` branche
- Github action poběží jenom na tag
```
on:
  push:
    tags:        
      - v1.**
```
- Nastaví se reviewer na @zoul, @pionl, @met 
- Zbytek už známe :)

**Comment by pionl** [comment]
Taky to tak půjde, ale přijdeme o to "review". Ale jestli se nepletu, tak actions by šlo nastavit tak, že to někdo musí schválit ne?

**Comment by zoul** [comment]
Jo, to je škoda, ten PR funguje jako pěkný nástroj pro release. A Actions AFAIK žádné potvrzování nemají, počítá se právě s tím, že tuhle část řeší PR. Ještě nad tím podumám.

**Comment by pionl** [comment]
@zoul připravuji tool na to potvrzování tak pak to můžeme použít

**Comment by pionl** [comment]
@zoul bude potřeba zapisovat číslo buildu do depozitáře - nyní nejde oTAGOVAT release :)

**Comment by pionl** [comment]
```
agvtool what-version
Current version of project Movapp is:
    2
```

🤔

**Comment by pionl** [comment]
Jo to bude tím UI tests projektem
