### ISSUE TITLE
Přidat deployment pipeline pro automatický upload binárek do App Storu

### ISSUE THREAD

**Issue by zoul** [cesko-digital/movapp-apple#8]
Průběžné TODO:

* [x] Zavést celoorganizační repo pro certifikáty
* [x] Nastavit Fastlane v projektu
* [x] Zprovoznit podepisování v GitHub Actions
* [x] Zavést release větev
* [x] Udělat GitHub Action pro upload z release větve

**Comment by pionl** [comment]
@zoul Můžeme spíš udělat release branch místo dev větev?

Jsem zvyklý a myslím, že je to lepší, míst master/main větev jako vývoj.  Doporučuji spíš toto, ale nechám na vás.

- Co se týče release vždy máme tagy kterým uděláme release (nebo případně z master pokud je to test).
- když někdo jde pracovat na něčem, vždy vychází z master, která je výchozí takže nemusí nic přepínat atd. Je to UX jednoduší.
- Když je potřeba udělat hotifx, vychází se z poslední stable tagu a udělá se jiný branch
- do masteru jdou "schválené/stabilnější" věci - vše jde přes PR a je možnost deploynout PR

**Comment by zoul** [comment]
Jestli ti dobře rozumím, tak je to jen terminologický rozdíl. Chceme mít dvě větve – na jedné se pracuje a je nastavená jako výchozí na GitHubu, do druhé se to přelívá v jasně daných momentech pro release. Na tom se shodujeme, ne? Pokud ano, je mně docela jedno, jak budeme které větvi říkat. Klidně můžeme nechat současnou pod názvem `main` jako tu pracovní, integrační, a založit větev `release`.

**Comment by pionl** [comment]
Klidně, nechám to na tobě. Je to jenom zvyklost. 

Může být vždy jenom 1 "test-flight" aplikace takže většinou to právě přemažeme. Používali jsme to když PR chtěl testing schválit a nechtěli jsme to dávat do main dokud to nebylo vyzkoušené - měli jsme dost strict policy že master je stable (tj, každý musel dělat rebase a držet si aktuální branch).

**Comment by zoul** [comment]
Hotovo, frčí.
