### ISSUE TITLE
Přidat SK / PL jazyky

### ISSUE THREAD

**Issue by pionl** [cesko-digital/movapp-apple#97]
- úprava onboardingu
- úprava settings
- **BUG** když mám vybranou abecedu a přepnu jazyk a vrátím se k abecedě tak vybraná abeceda není

**Comment by pionl** [comment]
@kubito bug se nám podařilo opravit?

**Comment by met** [comment]
Když přepnu jazyk, nezaktualizuje se abeceda.
Teď jsem měl rodný jazyk polštinu, v nastavení Movappu jsem přepl na rodný jazyk čeština, otevřel jsem okno s abecedou - nahoře se správně zaktualizovaly záložky abeced (Ukrajinská abeceda - Česká abeceda - viz screenshot), ale ani jedna z nich není vybraná a v celém okně vidím stále původní polskou abecedu. 

![50F97214-3092-4D2D-8825-9728F33DAD33](https://user-images.githubusercontent.com/59498/187734179-912166aa-f6c5-4a13-98bf-f5d96c18e668.jpeg)

**Comment by met** [comment]
Když spustím aplikaci se slovenským nebo polským jazykem, v boardingu chybí překlad (na screenshotu vlevo nahoře) "on_boarding_back".

![765225CC-3541-4B55-875E-9303A6C0090A](https://user-images.githubusercontent.com/59498/187734959-3521f243-7ffc-43f0-9bce-16c19d9e2fb8.jpeg)

**Comment by pionl** [comment]
U polske abecedy se nevejde dci posmeno, trochu byl zvetsil sirku slideru.

![image](https://user-images.githubusercontent.com/1878831/188496159-ff5f4d36-5624-4d76-adc2-bc7a7afe0cfb.jpeg)

**Comment by pionl** [comment]
Nejak se me podarilo rozbit nacitani polske abecedy - po prepnuti na sk uz zpet polskou nedam.

https://user-images.githubusercontent.com/1878831/188496367-97ba02d1-d78d-4992-a0a0-041213c36732.MOV

**Comment by pionl** [comment]
Zapomněl jsem pridat obrazky do aplikace a v sekci pro deti pak chybeji - je potreba je z ios smazat a vlozit aktualni sadu z movapp-data

**Comment by pionl** [comment]
Pokud rozkliknu ve slovnicku sekci a jdu do nastaveni prepnout jazyk tak se me zobrazuje puvodni jazyk, bude to tim ze je tam temporary list ktery bude potreba pregenrovat pri zmene jazyku.

https://user-images.githubusercontent.com/1878831/188496769-f0bbd395-0a13-44c1-add9-5f6115ee6baa.MOV

**Comment by met** [comment]
Máme pár drobných oprav do slovenské lokalizace

 https://cesko-digital.slack.com/archives/C036GLKL7ME/p1662442438911749?thread_ts=1662311311.467089&cid=C036GLKL7ME

**Comment by met** [comment]
Aktualizoval jsem team.json (Daryna změnila přijmení a přidal jsem dva nové členy - ano, včetně tady Jakuba, ať v té nové iOS verzi už je vidět tvé jméno).

Prosím updatni si team.json v iOS na tuhle verzi:

https://github.com/cesko-digital/movapp-data/blob/1f192bdbfd87d512b405cc325b8e0807438ff0e4/data/team.json

**Comment by met** [comment]
**Technická:** jelikož se nám to teď rozlezlo do řady chyb/úkolů v jednom github issues, je složitější sledovat, které ještě zbývají a které už jsou hotové. 
Pokud to nechceme rozdělit na separání issues, doporučuji využít github checkboxy a k hlášení přidávat text:
 `- [ ] popis úkolu`

Github z toho automaticky vytvoří checkbox (víz mé dva komentáře výše), který lze po vyřešení úkolu odškrtnout a je snadno vidět, co ještě zbývá.

**Comment by pionl** [comment]
Může být ale třeba @kubito používá emoticony na to a podle toho to vidíš jestli je to nebo ne. Taky to tak používáme na Gitlabu a je stejné jako `- [ ]` které je "složitější" na psaní

**Comment by met** [comment]
Ok, emotikonu jsem si nevsiml. Budu se po nich priste divat 👍
